#!/usr/bin/env node

import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
  Tool,
} from "@modelcontextprotocol/sdk/types.js";
import { readFile, writeFile, mkdir } from "fs/promises";
import { extname, join } from "path";
import JSZip from "jszip";
import pngToIco from "png-to-ico";
import sharp from "sharp";

const GEMINI_API_URL = "https://generativelanguage.googleapis.com/v1beta/models";

interface GeminiResponse {
  candidates?: Array<{
    content?: {
      parts?: Array<{
        text?: string;
        inlineData?: {
          mimeType: string;
          data: string;
        };
      }>;
    };
  }>;
  error?: {
    message: string;
  };
}

interface InputImage {
  data: string;
  mimeType: string;
}

interface FaviconOptions {
  appName?: string;
  shortName?: string;
  themeColor?: string;
  backgroundColor?: string;
  includeReadme?: boolean;
}

const FAVICON_SIZES = [
  { size: 16, name: "favicon-16x16.png" },
  { size: 32, name: "favicon-32x32.png" },
  { size: 180, name: "apple-touch-icon.png" },
  { size: 192, name: "android-chrome-192x192.png" },
  { size: 512, name: "android-chrome-512x512.png" },
];
const ICO_SIZES = [16, 32, 48];

function getMimeType(filePath: string): string {
  const ext = extname(filePath).toLowerCase();
  const mimeTypes: Record<string, string> = {
    '.png': 'image/png',
    '.jpg': 'image/jpeg',
    '.jpeg': 'image/jpeg',
    '.webp': 'image/webp',
    '.gif': 'image/gif',
  };
  return mimeTypes[ext] || 'image/png';
}

function getHtmlSnippet(): string {
  return `<link rel="icon" href="/favicon.ico" sizes="any">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">`;
}

function createManifestContent(options: FaviconOptions): string {
  const appName = options.appName || "My App";
  const shortName = options.shortName || "App";
  const themeColor = options.themeColor || "#ffffff";
  const backgroundColor = options.backgroundColor || "#ffffff";

  const manifest = {
    name: appName,
    short_name: shortName,
    icons: [
      {
        src: "/android-chrome-192x192.png",
        sizes: "192x192",
        type: "image/png",
      },
      {
        src: "/android-chrome-512x512.png",
        sizes: "512x512",
        type: "image/png",
      },
    ],
    theme_color: themeColor,
    background_color: backgroundColor,
    display: "standalone",
  };

  return JSON.stringify(manifest, null, 2);
}

function createReadmeContent(): string {
  return `Favicon Package Generated by mcp-nano-banana

Your package includes:
- favicon.ico: Multi-size icon for legacy browsers.
- favicon-16x16.png: For browser tabs.
- favicon-32x32.png: For browser tabs (higher resolution).
- apple-touch-icon.png: For iOS home screens.
- android-chrome-192x192.png: For Android devices.
- android-chrome-512x512.png: For Android devices (higher resolution).
- site.webmanifest: For PWA and modern browser integration.

How to use:
1. Place all files in the root directory of your website.
2. Add the following lines to the <head> of your HTML files:

${getHtmlSnippet()}
`;
}

async function loadImageFromPath(filePath: string): Promise<InputImage> {
  const buffer = await readFile(filePath);
  const base64 = buffer.toString('base64');
  const mimeType = getMimeType(filePath);
  return { data: base64, mimeType };
}

async function buildFaviconFiles(
  baseImage: Buffer,
  options: FaviconOptions
): Promise<Map<string, Buffer>> {
  const files = new Map<string, Buffer>();

  const icoPngBuffers = await Promise.all(
    ICO_SIZES.map((size) =>
      sharp(baseImage)
        .resize(size, size, { fit: "fill" })
        .png()
        .toBuffer()
    )
  );
  const icoBuffer = await pngToIco(icoPngBuffers);
  files.set("favicon.ico", icoBuffer);

  for (const { size, name } of FAVICON_SIZES) {
    const resized = await sharp(baseImage)
      .resize(size, size, { fit: "fill" })
      .png()
      .toBuffer();
    files.set(name, resized);
  }

  const manifestContent = createManifestContent(options);
  files.set("site.webmanifest", Buffer.from(manifestContent, "utf8"));

  if (options.includeReadme !== false) {
    files.set("README.md", Buffer.from(createReadmeContent(), "utf8"));
  }

  return files;
}

async function writeFaviconFiles(
  outputDir: string,
  files: Map<string, Buffer>
): Promise<void> {
  await mkdir(outputDir, { recursive: true });
  const writes = Array.from(files.entries()).map(([name, data]) =>
    writeFile(join(outputDir, name), data)
  );
  await Promise.all(writes);
}

async function createFaviconZip(files: Map<string, Buffer>): Promise<Buffer> {
  const zip = new JSZip();
  for (const [name, data] of files.entries()) {
    zip.file(name, data);
  }
  return zip.generateAsync({ type: "nodebuffer" });
}

function buildIconPrompt(userPrompt: string): string {
  return `A professional, modern, square app icon. Vector art style. Centered object. The icon should represent: "${userPrompt}". The background should follow the user's description. The icon must be clear, simple, and easily recognizable at small sizes. No text unless specified.`;
}

const tools: Tool[] = [
  {
    name: "generate_image",
    description: "Generate an image using Google Nano Banana (Gemini) AI model. Can generate from text only, or use one or more reference images (up to 14) to guide generation.",
    inputSchema: {
      type: "object",
      properties: {
        prompt: {
          type: "string",
          description: "Text description of the image to generate or instructions for editing/combining reference images",
        },
        imagePaths: {
          type: "array",
          items: {
            type: "string",
          },
          description: "Optional array of file paths to reference images (up to 14). Supports png, jpg, jpeg, webp, gif.",
        },
        model: {
          type: "string",
          enum: ["gemini-2.5-flash-image", "gemini-3-pro-image-preview"],
          default: "gemini-3-pro-image-preview",
          description: "Model to use: gemini-2.5-flash-image (fast) or gemini-3-pro-image-preview (high quality, default)",
        },
        aspectRatio: {
          type: "string",
          enum: ["1:1", "16:9", "9:16", "4:3", "3:4", "2:3", "3:2", "4:5", "5:4", "21:9", "1:4", "4:1", "1:8", "8:1"],
          default: "1:1",
          description: "Aspect ratio of the generated image. Additional ratios (1:4, 4:1, 1:8, 8:1) available on gemini-3.1-flash-image-preview.",
        },
        resolution: {
          type: "string",
          enum: ["512", "1K", "2K", "4K"],
          default: "1K",
          description: "Resolution of the generated image. 512 only on gemini-3.1-flash-image-preview. Nano Banana Pro supports 1K, 2K, 4K.",
        },
        outputFormat: {
          type: "string",
          enum: ["png", "jpeg", "webp"],
          default: "png",
          description: "Output image format",
        },
        outputPath: {
          type: "string",
          description: "File path to save the generated image. If not provided, image data is returned inline.",
        },
      },
      required: ["prompt"],
    },
  },
  {
    name: "generate_favicons",
    description: "Generate a full favicon package from a prompt or an existing image. Creates PNG sizes, a web manifest, and optional README, then writes files and/or a ZIP bundle.",
    inputSchema: {
      type: "object",
      properties: {
        prompt: {
          type: "string",
          description: "Text description for generating a master icon (square). Required if imagePath is not provided.",
        },
        imagePath: {
          type: "string",
          description: "Path to an existing master icon image. If provided, prompt is optional.",
        },
        model: {
          type: "string",
          enum: ["gemini-2.5-flash-image", "gemini-3-pro-image-preview"],
          default: "gemini-3-pro-image-preview",
          description: "Model to use when generating the master icon from a prompt.",
        },
        outputDir: {
          type: "string",
          description: "Directory to write individual favicon files.",
        },
        outputPath: {
          type: "string",
          description: "File path to save the favicon ZIP package.",
        },
        returnZipBase64: {
          type: "boolean",
          default: false,
          description: "When true and outputPath is not provided, return the ZIP as base64 text.",
        },
        appName: {
          type: "string",
          description: "Manifest app name. Default: My App.",
        },
        shortName: {
          type: "string",
          description: "Manifest short name. Default: App.",
        },
        themeColor: {
          type: "string",
          description: "Manifest theme color. Default: #ffffff.",
        },
        backgroundColor: {
          type: "string",
          description: "Manifest background color. Default: #ffffff.",
        },
        includeReadme: {
          type: "boolean",
          default: true,
          description: "Include README.md in the package.",
        },
      },
    },
  },
];

export async function generateImage(
  prompt: string,
  images: InputImage[] = [],
  model: string = "gemini-3-pro-image-preview",
  aspectRatio: string = "1:1",
  resolution: string = "1K",
  outputFormat: string = "png"
): Promise<{ text?: string; imageData?: string; mimeType?: string; modelUsed?: string; fallback?: boolean }> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error("GEMINI_API_KEY environment variable is not set");
  }

  // Build parts array: text prompt first, then any images
  const parts: Array<{ text: string } | { inlineData: { mimeType: string; data: string } }> = [
    { text: prompt }
  ];

  for (const image of images) {
    parts.push({
      inlineData: {
        mimeType: image.mimeType || "image/png",
        data: image.data,
      },
    });
  }

  const makeRequest = async (currentModel: string) => {
    return fetch(
      `${GEMINI_API_URL}/${currentModel}:generateContent`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-goog-api-key": apiKey,
        },
        body: JSON.stringify({
          contents: [{ parts }],
          generationConfig: {
            responseModalities: ["TEXT", "IMAGE"],
            imageConfig: {
              aspectRatio: aspectRatio,
              imageSize: resolution,
            },
          },
        }),
      }
    );
  };

  let response = await makeRequest(model);
  let usedModel = model;
  let didFallback = false;

  // If Pro model fails with quota/rate limit, fallback to Flash
  if (!response.ok && model === "gemini-3-pro-image-preview") {
    const status = response.status;
    if (status === 429 || status === 403 || status === 402) {
      usedModel = "gemini-2.5-flash-image";
      didFallback = true;
      response = await makeRequest(usedModel);
    }
  }

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Gemini API error: ${response.status} - ${errorText}`);
  }

  const data: GeminiResponse = await response.json();

  if (data.error) {
    throw new Error(`Gemini API error: ${data.error.message}`);
  }

  const responseParts = data.candidates?.[0]?.content?.parts;
  if (!responseParts || responseParts.length === 0) {
    throw new Error("No content generated");
  }

  const result: { text?: string; imageData?: string; mimeType?: string; modelUsed?: string; fallback?: boolean } = {
    modelUsed: usedModel,
    fallback: didFallback,
  };

  for (const part of responseParts) {
    if (part.text) {
      result.text = part.text;
    }
    if (part.inlineData) {
      result.imageData = part.inlineData.data;
      result.mimeType = part.inlineData.mimeType;
    }
  }

  return result;
}


const server = new Server(
  {
    name: "mcp-nano-banana",
    version: "1.0.0",
  },
  {
    capabilities: {
      tools: {},
    },
  }
);

server.setRequestHandler(ListToolsRequestSchema, async () => {
  return { tools };
});

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;

  try {
    if (name === "generate_image") {
      const { prompt, imagePaths, model, aspectRatio, resolution, outputFormat, outputPath } = args as {
        prompt: string;
        imagePaths?: string[];
        model?: string;
        aspectRatio?: string;
        resolution?: string;
        outputFormat?: string;
        outputPath?: string;
      };

      // Load images from disk paths
      const images: InputImage[] = [];
      if (imagePaths && imagePaths.length > 0) {
        for (const path of imagePaths) {
          const image = await loadImageFromPath(path);
          images.push(image);
        }
      }

      const result = await generateImage(
        prompt,
        images,
        model,
        aspectRatio,
        resolution,
        outputFormat
      );

      const content: Array<{ type: string; text?: string; data?: string; mimeType?: string }> = [];

      // Report model used and fallback status
      let statusText = `Model used: ${result.modelUsed}`;
      if (result.fallback) {
        statusText += ` (fallback from gemini-3-pro-image-preview due to quota/rate limit)`;
      }

      if (result.text) {
        statusText += `\n\n${result.text}`;
      }

      content.push({ type: "text", text: statusText });

      if (result.imageData && result.mimeType) {
        // Save to file if outputPath provided
        if (outputPath) {
          await writeFile(outputPath, Buffer.from(result.imageData, 'base64'));
          content.push({ type: "text", text: `Image saved to: ${outputPath}` });
        } else {
          content.push({
            type: "image",
            data: result.imageData,
            mimeType: result.mimeType,
          });
        }
      }

      return { content };
    }

    if (name === "generate_favicons") {
      const {
        prompt,
        imagePath,
        model,
        outputDir,
        outputPath,
        returnZipBase64,
        appName,
        shortName,
        themeColor,
        backgroundColor,
        includeReadme,
      } = args as {
        prompt?: string;
        imagePath?: string;
        model?: string;
        outputDir?: string;
        outputPath?: string;
        returnZipBase64?: boolean;
        appName?: string;
        shortName?: string;
        themeColor?: string;
        backgroundColor?: string;
        includeReadme?: boolean;
      };

      if (!prompt && !imagePath) {
        throw new Error("Either prompt or imagePath must be provided");
      }

      if (!outputDir && !outputPath && !returnZipBase64) {
        throw new Error("Provide outputDir, outputPath, or set returnZipBase64 to true");
      }

      let baseImageBuffer: Buffer;

      if (imagePath) {
        const loaded = await loadImageFromPath(imagePath);
        baseImageBuffer = Buffer.from(loaded.data, "base64");
      } else {
        const iconPrompt = buildIconPrompt(prompt || "");
        const result = await generateImage(
          iconPrompt,
          [],
          model,
          "1:1",
          "png"
        );

        if (!result.imageData) {
          throw new Error("No image generated for favicon package");
        }

        baseImageBuffer = Buffer.from(result.imageData, "base64");
      }

      const options: FaviconOptions = {
        appName,
        shortName,
        themeColor,
        backgroundColor,
        includeReadme,
      };

      const files = await buildFaviconFiles(baseImageBuffer, options);

      if (outputDir) {
        await writeFaviconFiles(outputDir, files);
      }

      let zipBuffer: Buffer | undefined;
      if (outputPath || returnZipBase64) {
        zipBuffer = await createFaviconZip(files);
      }

      const content: Array<{ type: string; text?: string; data?: string; mimeType?: string }> = [];
      content.push({
        type: "text",
        text: `Favicon package ready.\n\nHTML snippet:\n${getHtmlSnippet()}`,
      });

      if (outputDir) {
        content.push({ type: "text", text: `Files written to: ${outputDir}` });
      }

      if (outputPath && zipBuffer) {
        await writeFile(outputPath, zipBuffer);
        content.push({ type: "text", text: `ZIP saved to: ${outputPath}` });
      } else if (returnZipBase64 && zipBuffer) {
        content.push({
          type: "text",
          text: `ZIP (base64): ${zipBuffer.toString("base64")}`,
        });
      }

      return { content };
    }

    throw new Error(`Unknown tool: ${name}`);
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    return {
      content: [{ type: "text", text: `Error: ${errorMessage}` }],
      isError: true,
    };
  }
});

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("Nano Banana MCP server running on stdio");
}

main().catch(console.error);
